# This is a basic workflow to help you get started with Actions

name: Publish to Github Page

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Make envfile
        run: |
          cat << EOF > .env
          NODE_ENV=${{secrets.NODE_ENV}}
          PORT=${{secrets.PORT}}
          MAIL_USER=${{secrets.MAIL_USER}}
          MAIL_PASS=${{secrets.MAIL_PASS}}
          MAIL_HOST=${{secrets.MAIL_HOST}}
          MAIL_PORT=${{secrets.MAIL_PORT}}
          MAIL_DESTINATION=${{secrets.MAIL_DESTINATION}}
          RECAPTCHA_SECRET_KEY=${{secrets.RECAPTCHA_SECRET_KEY}}
          EOF

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run clean
      - run: npm run build --if-present
      # - run: pm2 start --name qc3 server/index.js --watch # for the initial deployment
      - run: pm2 restart qc3 # for continuous deployment
