# This is a basic workflow to help you get started with Actions

name: Publish to Github Page

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Create env file
        run: |
          echo "Creating .env for ${{ secrets.MAIL_USER }}"
          touch .env
          echo NODE_ENV=production >> .env
          echo PORT=9000 >> .env
          echo MAIL_USER=${{ secrets.MAIL_USER }} >> .env
          echo MAIL_PASS=${{ secrets.MAIL_PASS }} >> .env
          echo MAIL_HOST=${{ secrets.MAIL_HOST }} >> .env
          echo MAIL_PORT=${{ secrets.MAIL_PORT }} >> .env
          echo MAIL_DESTINATION=${{ secrets.MAIL_DESTINATION }} >> .env
          echo RECAPTCHA_SECRET_KEY=${{ secrets.RECAPTCHA_SECRET_KEY }} >> .env
          cat .env
      - run: npm run build --if-present
      - run: cp -r public /var/www/quebec3/
      - run: pm2 delete qc3 # start PM2 clean slate
      - run: pm2 start --name qc3 /var/www/quebec3/server/index.js --watch
